#pragma once
#include <Windows.h>
#include <vector>
#include <list>
#include <algorithm>
#include <d2d1.h>
#include <string>
#include <map>
#include "Math.h"
#include "Enums.h"
#include "Time.h"
#include <cassert>
#include <dwrite.h>
#include <dxgi1_4.h>
#include <bitset>